WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: pytz in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (2020.4)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: geocoder==1.38.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (1.38.1)
Requirement already satisfied: requests in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (2.24.0)
Requirement already satisfied: six in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (1.15.0)
Requirement already satisfied: ratelim in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (0.1.6)
Requirement already satisfied: future in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (0.17.1)
Requirement already satisfied: click in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (7.1.2)
Requirement already satisfied: decorator in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from ratelim->geocoder==1.38.1) (4.4.2)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (3.0.4)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: fuzzywuzzy==0.18.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (0.18.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: text2numde==1.0.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (1.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: sounddevice==0.4.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (0.4.1)
Requirement already satisfied: CFFI>=1.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from sounddevice==0.4.1) (1.14.4)
Requirement already satisfied: pycparser in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from CFFI>=1.0->sounddevice==0.4.1) (2.20)
C:\Users\jfrei\Anaconda3\envs\11_ui\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: python-dateutil==2.8.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from python-dateutil==2.8.1) (1.15.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: num2words==0.5.10 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (0.5.10)
Requirement already satisfied: docopt>=0.6.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from num2words==0.5.10) (0.6.2)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: text2numde==1.0.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (1.0)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: pyowm==3.1.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (3.1.1)
Requirement already satisfied: geojson<3,>=2.3.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from pyowm==3.1.1) (2.5.0)
Requirement already satisfied: requests<3,>=2.20.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from pyowm==3.1.1) (2.24.0)
Requirement already satisfied: PySocks<2,>=1.7.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from pyowm==3.1.1) (1.7.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3,>=2.20.0->pyowm==3.1.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3,>=2.20.0->pyowm==3.1.1) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3,>=2.20.0->pyowm==3.1.1) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3,>=2.20.0->pyowm==3.1.1) (3.0.4)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: geocoder==1.38.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (1.38.1)
Requirement already satisfied: requests in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (2.24.0)
Requirement already satisfied: six in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (1.15.0)
Requirement already satisfied: ratelim in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (0.1.6)
Requirement already satisfied: future in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (0.17.1)
Requirement already satisfied: click in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from geocoder==1.38.1) (7.1.2)
Requirement already satisfied: decorator in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from ratelim->geocoder==1.38.1) (4.4.2)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests->geocoder==1.38.1) (3.0.4)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: pycountry==20.7.3 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (20.7.3)
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: wikipedia==1.4.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from wikipedia==1.4.0) (4.9.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from wikipedia==1.4.0) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia==1.4.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia==1.4.0) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia==1.4.0) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia==1.4.0) (3.0.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\jfrei\anaconda3\envs\11_ui\lib\site-packages (from beautifulsoup4->wikipedia==1.4.0) (2.1)
Fitting lookup intent parser...
Fitted lookup intent parser in 0:00:00.002991
Fitting probabilistic intent parser...
Fitting LogRegIntentClassifier...
LogRegIntentClassifier in 0:00:03.562618
Fitting getTime slot filler...
Fitted CRFSlotFiller in 0:00:00.540690
Fitting musicstream slot filler...
Fitted CRFSlotFiller in 0:00:02.050118
Fitting reminder slot filler...
Fitted CRFSlotFiller in 0:00:23.856657
Fitting stop slot filler...
Fitted CRFSlotFiller in 0:00:00.001135
Fitted probabilistic intent parser in 0:00:30.017604
Fitted NLU engine in 0:00:30.717212
Traceback (most recent call last):
  File "main_11.py", line 50, in CreatePopupMenu
    def CreatePopupMenu(self):
KeyboardInterrupt
